// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Entities
{
    public partial class ToDoListContextModel
    {
        partial void Initialize()
        {
            var list = ListEntityType.Create(this);
            var task = TaskEntityType.Create(this);
            var user = UserEntityType.Create(this);

            ListEntityType.CreateForeignKey1(list, user);
            TaskEntityType.CreateForeignKey1(task, list);

            ListEntityType.CreateAnnotations(list);
            TaskEntityType.CreateAnnotations(task);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
